### ISSUE TITLE
Display time zones in event list

### ISSUE THREAD

**Issue by bascht** [indieweb/events.indieweb.org#3]
It'd be great if the event list on the home page would show the time zones of the events

Nottingham is `Europe/London` whereas Karlsruhe is `Europe/Berlin`: 

![Screenshot-2020-07-08-190113](https://user-images.githubusercontent.com/51264/86948474-78b51f80-c14d-11ea-838e-172c8345f3e1.png)

the event pages do list the correct time zones:
![Screenshot-2020-07-08-190122](https://user-images.githubusercontent.com/51264/86948487-7eab0080-c14d-11ea-86fb-baacca25893a.png)

**Comment by aaronpk** [comment]
There were two reasons I didn't include the timezones in the main list:

1) For in-person events, people will identify the location of the event from the title and assume local time, so the timezone would not provide any new information
2) Adding additional text will clutter the display

Point 1 is not super relevant anymore since pretty much all events are virtual now and anyone can attend anything. Point 2 still stands however.

Do you have a suggestion for a way to indicate the timezone in a meaningful but not noisy way in the list?

**Comment by dshanske** [comment]
Can you detect browser timezone and convert?

**Comment by bascht** [comment]
@aaronpk Come to think of it, (1) makes a lot of sense – my confusion came from the assumption that all events are virtual nowadays. :D

The only thing I can think of, would be a `title=""` on the `<time>` tag:

![hwc](https://user-images.githubusercontent.com/51264/87127650-8f16c480-c28e-11ea-8e5b-d21d1afeb6a1.gif)

**Comment by aaronpk** [comment]
Converting to local timezone may lead to more confusion unless it's made very clear that you are viewing a converted time.

The title attribute (plus also maybe even a JS hovercard) is a good suggestion though!

**Comment by aaronpk** [comment]
This is done! I did one better and included a timezone conversion to your browser's timezone in the tooltip too!
<img width="519" alt="Screen Shot 2020-07-10 at 10 22 05 AM" src="https://user-images.githubusercontent.com/113001/87181477-41528a00-c297-11ea-8a82-b24daabcfae5.png">
